---
- name: Upload {{ ranger_hdfs_dist_file }}
  copy:
    src: "files/{{ ranger_hdfs_dist_file }}"
    dest: /tmp

- name: Extract {{ ranger_hdfs_dist_file }}
  unarchive:
    src: "/tmp/{{ ranger_hdfs_dist_file }}"
    dest: "{{ hadoop_root_dir }}"
    group: root
    owner: root
    remote_src: yes

- name: Create symbolic link to Ranger installation
  file:
    src: "{{ hadoop_root_dir }}/{{ ranger_hdfs_release }}"
    dest: "{{ ranger_hdfs_install_dir }}"
    state: link

- name: Template install.properties
  template:
    src: install_hdfs.properties.j2
    dest: "{{ ranger_hdfs_install_dir }}/install.properties"

# Ranger installation scripts finds hadoop at "../hadoop" to add necessary properties to hdfs-site.xml, generate the ranger-*.xml
# It can also be configured with COMPONENT_INSTALL_DIR_NAME but we still have to make /opt/hadoop/etc/hadoop a symbolic link to /etc/hadoop/conf.nn to get the configurations at the right place
# TODO: find a better way to do this

- name: Move etc/hadoop in {{ hadoop_install_dir }}
  command: |
    rm -rf {{ hadoop_install_dir }}/etc/hadoop.bk
    mv {{ hadoop_install_dir }}/etc/hadoop {{ hadoop_install_dir }}/etc/hadoop.bk

- name: Create symbolic link from etc/hadoop in {{ hadoop_install_dir }} to actual Namenode config dir
  file:
    src: "{{ hadoop_nn_conf_dir }}"
    dest: "{{ hadoop_install_dir }}/etc/hadoop"
    state: link

- name: Run enable-hdfs-plugin.sh
  shell: |
    cd {{ ranger_hdfs_install_dir }}
    export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk
    ./enable-hdfs-plugin.sh

# We also need to fix the path of the ranger-policymgr-ssl.xml containing the trustore properties in ranger-hdfs-security.xml
- name: Fix the path of ranger-policymgr-ssl.xml in ranger-hdfs-security.xml
  lineinfile:
    path: "{{ hadoop_nn_conf_dir }}/ranger-hdfs-security.xml"
    regexp: '<value>/etc/hadoop/conf/ranger-policymgr-ssl.xml</value>'
    line: '                <value>/etc/hadoop/conf.nn/ranger-policymgr-ssl.xml</value>'
    backrefs: yes

- name: Create HDFS service
  run_once: true
  uri:
    url: "{{ ranger_hdfs_install_properties.POLICY_MGR_URL }}/service/plugins/services"
    method: POST
    body:
      name: "{{ ranger_hdfs_install_properties.REPOSITORY_NAME }}"
      isEnabled: true
      configs:
        username: hdfs
        password: hdfs
        fs.default.name: hdfs://mycluster
        hadoop.security.authorization: true
        hadoop.security.authentication: kerberos
        dfs.datanode.kerberos.principal: dn/_HOST@TDP.XHERMAND
        dfs.namenode.kerberos.principal: nn/_HOST@TDP.XHERMAND
        hadoop.rpc.protection: authentication
        #hadoop.security.auth_to_local: ""
      type: hdfs
    body_format: json
    force_basic_auth: yes
    user: admin
    password: "{{ ranger_admin_password }}"
    headers:
      Content-Type: application/json
    status_code: [200, 202,400]
    validate_certs: no
  #TODO fix below to remove code 400
  #register: reg_hdfs
  #failed_when: |
  #  'Duplicate service name' not in reg_hdfs.json.msgDesc and
  #  'already exists' not in reg_hdfs.json.msgDesc
