---
- import_role:
    name: tosit.tdp.hive.common
    tasks_from: install_hive

- name: Create configuration directory
  file:
    path: '{{ hive_s2_conf_dir }}'
    state: directory
    group: '{{ hadoop_group }}'
    owner: '{{ hive_user }}'

- name: Template Hiveserver2 service file
  template:
    src: hive-server2.service.j2
    dest: /usr/lib/systemd/system/hive-server2.service
