---
# Zookeeper directory properties
hadoop_root_dir: /opt/tdp
zookeeper_dist_release: zookeeper-3.4.6
zookeeper_dist_file: "{{ zookeeper_dist_release }}.tar.gz"
zookeeper_install_dir: "{{ hadoop_root_dir }}/zookeeper"
zookeeper_data_dir: "{{ zookeeper_install_dir }}/zkData"
zk_servers: |
  {{ groups['zk'] | 
     map('tosit.tdp.access_fqdn', hostvars) | 
     map('regex_replace', '^(.*)$', '\1:2888:3888') |
     list }}
