# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Ensure common kerberos installation tasks are performed
  ansible.builtin.import_role:
    name: tosit.tdp.utils.kerberos
    tasks_from: install

- name: Ensure hive user's principal and keytab exist
  ansible.builtin.import_role:
    name: tosit.tdp.utils.kerberos
    tasks_from: create_principal_keytab
  vars:
    principal: hive/{{ ansible_fqdn }}
    keytab: hive.service.keytab
    user: "{{ hive_user }}"
    group: "{{ hadoop_group }}"
    mode: "0600"
  when: krb_create_principals_keytabs

- name: Ensure hive user's keytab is working
  ansible.builtin.import_role:
    name: tosit.tdp.utils.kerberos
    tasks_from: check_secure_keytab
  vars:
    principal: hive/{{ ansible_fqdn }}
    keytab: hive.service.keytab
    user: "{{ hive_user }}"
    group: "{{ hadoop_group }}"
    mode: "0600"
  when: not krb_create_principals_keytabs
  
- name: Template jaas.conf
  ansible.builtin.template:
    src: jaas.conf.j2
    dest: "/etc/hive/conf.ms/jaas.conf"
    owner: root
    group: root
    mode: "644"
