# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Render capacity-scheduler.xml
  ansible.builtin.template:
    src: capacity-scheduler.xml.j2
    dest: '{{ hadoop_rm_conf_dir }}/capacity-scheduler.xml'
    owner: root
    group: root
    mode: "644"

- name: "Yarn scheduler | take kerberos ticket"
  ansible.builtin.command: kinit -kt /etc/security/keytabs/rm.service.keytab rm/{{ ansible_fqdn }}@{{ realm }}
  become_user: yarn

- name: "Yarn scheduler | Refresh Queues"
  ansible.builtin.command: /usr/bin/yarn rmadmin -refreshQueues
  become_user: yarn
