# Ranger YARN properties
ranger_yarn_release: ranger-2.0.1-TDP-0.1.0-SNAPSHOT-yarn-plugin
ranger_yarn_dist_file: "{{ ranger_yarn_release }}.tar.gz"
ranger_yarn_install_dir: "{{ hadoop_root_dir }}/ranger-yarn-plugin"
ranger_yarn_install_properties:
  POLICY_MGR_URL: "https://{{ groups['ranger_admin'][0] | tosit.tdp.access_fqdn(hostvars) }}:6182"
  REPOSITORY_NAME: yarn-tdp
