# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- import_playbook: ../zookeeperkafka_client_install.yml
- import_playbook: ../zookeeperkafka_jmx-exporter_config.yml
- import_playbook: ../zookeeperkafka_server_install.yml
- import_playbook: ../zookeeperkafka_kerberos_install.yml
- import_playbook: ../zookeeperkafka_client_config.yml
# zookeeperkafka_install
- import_playbook: ../zookeeperkafka_server_config.yml
# zookeeperkafka_config
- import_playbook: ../zookeeperkafka_server_start.yml
# zookeeperkafka_server_init
# zookeeperkafka_start
# zookeeperkafka_init
